name: sfcvm-ci

on:
  push:
    branches: [ foo ]

jobs:
  sfcvm-build-standalone-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/target" >> $GITHUB_ENV
    - name: checkout sfcvm main
      uses: actions/checkout@v2
      with: 
        ref: main 
    - name: build sfcvm
      run: ./.github/scripts/sfcvm-build.sh
      shell: bash
    - name: test sfcvm standalone
      run: ./.github/scripts/sfcvm-test-standalone.sh
      shell: bash
#    - name: Start SSH via Ngrok
#      if: ${{ success() }}
#      uses: luchihoratiu/debug-via-ssh@main
#      with:
#            NGROK_AUTH_TOKEN: ${{ secrets.NGROK_TOKEN }}
#            NGROK_TIMEOUT: 3000
#            SSH_PASS: ${{ secrets.NGROK_SECRET }}

